"""Agent 契约、上下文、生成、校验与单轮 Pipeline 模块。"""

from intern_rag.agent.answer import (
    AnswerResult,
    Citation,
    compose_answer,
)
from intern_rag.agent.context import (
    ContextStrategy,
    build_context,
    context_item_from_result,
    format_context_item,
)
from intern_rag.agent.context_engine import (
    ContextBudgetError,
    ContextEngine,
    ContextEngineConfig,
    ContextInputs,
    ContextSegment,
    ConversationMessage,
    ManagedContext,
    MemoryItem,
    MixedTokenEstimator,
    ProfileFact,
    UserProfile,
)
from intern_rag.agent.context_policy import (
    ContextPlan,
    ContextPolicy,
    ContextPolicyConfig,
    ContextSignalExtractor,
    ContextSignals,
    rank_memories,
)
from intern_rag.agent.evidence import (
    EvidenceConfig,
    EvidenceDecision,
    ScoreGateConfig,
    check_evidence,
    load_evidence_config,
)
from intern_rag.agent.generation import (
    DeepSeekChatClient,
    FakeLlmClient,
    GenerationParseError,
    GenerationResult,
    LlmClient,
    LlmClientError,
    LlmTimeoutError,
    OpenAIResponsesClient,
    build_generation_prompt,
    generate_answer,
    parse_generation_result,
)
from intern_rag.agent.model_gateway import (
    build_model_gateway_from_config,
    GatewayProvider,
    ModelGateway,
    ModelGatewayConfig,
    ModelGatewayUnavailable,
)
from intern_rag.agent.pipeline import PipelineConfig, RagPipeline
from intern_rag.agent.schemas import (
    BuiltContext,
    ContextItem,
    RagRequest,
    RagResponse,
    RagStatus,
    RetrieverName,
    RouterName,
)
from intern_rag.agent.validation import (
    ValidationIssue,
    ValidationResult,
    validate_generation,
)

__all__ = [
    "AnswerResult",
    "BuiltContext",
    "Citation",
    "ContextItem",
    "ContextStrategy",
    "ContextBudgetError",
    "ContextEngine",
    "ContextEngineConfig",
    "ContextInputs",
    "ContextPlan",
    "ContextPolicy",
    "ContextPolicyConfig",
    "ContextSegment",
    "ContextSignalExtractor",
    "ContextSignals",
    "ConversationMessage",
    "ManagedContext",
    "MemoryItem",
    "MixedTokenEstimator",
    "ProfileFact",
    "UserProfile",
    "EvidenceConfig",
    "EvidenceDecision",
    "ScoreGateConfig",
    "DeepSeekChatClient",
    "FakeLlmClient",
    "GenerationParseError",
    "GenerationResult",
    "LlmClient",
    "LlmClientError",
    "LlmTimeoutError",
    "GatewayProvider",
    "build_model_gateway_from_config",
    "ModelGateway",
    "ModelGatewayConfig",
    "ModelGatewayUnavailable",
    "OpenAIResponsesClient",
    "PipelineConfig",
    "RagRequest",
    "RagPipeline",
    "RagResponse",
    "RagStatus",
    "RetrieverName",
    "RouterName",
    "build_context",
    "build_generation_prompt",
    "check_evidence",
    "load_evidence_config",
    "compose_answer",
    "context_item_from_result",
    "format_context_item",
    "generate_answer",
    "parse_generation_result",
    "rank_memories",
    "ValidationIssue",
    "ValidationResult",
    "validate_generation",
]
